services:
  - type: web
    name: j2c-alvaras
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
